services:
  app:
    image: ${DOCKER_USERNAME}/${APP_NAME}:latest
    container_name: ${APP_NAME}
    restart: unless-stopped
    environment:
      - DB_URL=spring_sec_asym_enc
      - DB_PORT=5432
       - DB_NAME=${PG_DB_DB_NAME}
      - DB_USERNAME=${PG_DB_USERNAME}
      - DB_PASSWORD=${PG_DB_PASSWORD}
    depends_on:
      - db # wait for postgres to start

  db:
    image: postgres:17.5
    container_name: spring_sec_asym_enc
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_DB_USERNAME}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:

# Docker Networks
networks:
  default:
    name: task_flows_default