spring:
  application:
    name: spring-security-asymmetric-encryption
  config: # read .env file
    import: optional:file:.env[.properties]
  profiles:
    active: local

# JWT Properties
app:
  security:
    jwt:
      access-token-expiration: 86400000 # 24 hours for local testing
      refresh-token-expiration: 604800000
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail